spring:
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/vacations
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: klimonov23
  flyway:
    baseline-on-migrate: true

server:
  port: 8081