spring:
main:
allow-circular-references: true
jpa:
hibernate:
ddl-auto: validate
show-sql: true
datasource:
url: jdbc:postgresql://localhost:5432/shop
driver-class-name: org.postgresql.Driver
username: postgres
password: klimonov23
flyway:
baseline-on-migrate: true
